spring.application.name=demoSecurity
server.port=8086

# Configuration des utilisateurs Spring Security
# Utilisateur principal
spring.security.user.name=matthieu
spring.security.user.password=dev2024
spring.security.user.roles=USER,ADMIN

# Configuration Thymeleaf pour le développement
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML